### ISSUE TITLE
Правила хода фигуры

### ISSUE THREAD

**Issue by lepeshkinff** [TheVenYear/chess#1]
сделай правила хода конкретной фигуры расширением для перечисления FigureType
тогда королеве не нужно будет создавать сущности Castle и Bishop для получения ходов

примерно так должно получиться 
FigureType.Bishop.GetMoves(Cell current, IEnumerable<Cell> field)

**Comment by TheVenYear** [comment]
Вроде, готово

**Comment by lepeshkinff** [comment]
а git push не забыл?

**Comment by TheVenYear** [comment]
Я додик, кончено забыл. Вроде запушил

**Comment by lepeshkinff** [comment]
остальное-то доделывать будешь?

**Comment by TheVenYear** [comment]
У меня сейчас практика, пока нет времени
